export enum Tech {
    // Languages
    Java,
    JavaScript,
    TypeScript,
    CSharp,
    // Frameworks/Libraries
    Spring,
    DotNet,
    Blazor,
    NodeJS,
    React,
    NextJS,
    HTML,
    CSS,
    Sass,
    Bootstrap,
    Tailwind,
    // Databases
    MongoDB,
    MySQL,
    CosmosDB,
    SqlServer,
    PostgreSQL,
}

export const techDealer = {
    [Tech.Java]: { label: "Java", char: `\ue738` },
    [Tech.JavaScript]: { label: "JavaScript", char: `\ue781` },
    [Tech.TypeScript]: { label: "TypeScript", char: `\ue8ca` },
    [Tech.CSharp]: { label: "C#", char: `\ue648` },
    [Tech.Spring]: { label: "Spring framework", char: `\ue8ac` },
    [Tech.DotNet]: { label: ".NET framework", char: `\udb82\udeae` },
    [Tech.Blazor]: { label: "Blazor web framework", char: `\ue765` },
    [Tech.NodeJS]: { label: "Node.js runtime environment", char: `\ued0d` },
    [Tech.React]: { label: "React library", char: `\ue7ba` },
    [Tech.NextJS]: { label: "Next.js web framework", char: `\ue83e` },
    [Tech.HTML]: { label: "HTML", char: `\ue736` },
    [Tech.CSS]: { label: "CSS", char: `\ue749` },
    [Tech.Sass]: { label: "Sassy CSS", char: `\ue74b` },
    [Tech.Bootstrap]: { label: "Bootstrap CSS framework", char: `\ue747` },
    [Tech.Tailwind]: { label: "Tailwind CSS", char: `\ue8ba` },
    [Tech.MongoDB]: { label: "MongoDB NoSQL database", char: `\ue7a4` },
    [Tech.MySQL]: { label: "MySQL database", char: `\ue704` },
    [Tech.CosmosDB]: { label: "CosmosDB SQL database", char: `\ue79f` },
    [Tech.SqlServer]: { label: "SQL Server database", char: `\ue64d` },
    [Tech.PostgreSQL]: { label: "PostgreSQL database", char: `\ue76e` },
};
